### ISSUE TITLE
could not install Lumina

### ISSUE THREAD

**Issue by zeevmindali** [dokun1/Lumina#31]
Dear Friend,

i followed your instruction and add the Lumina to Podfile.
did update,install
when i opened the Xcode after build , i getting build failed with 46 error.
i using deployment target of 10.3 (would like to use 11.0)
and xcode 9.1

what i doing wrong :(

**Comment by dokun1** [comment]
Hi! Can you share what your podfile looks like?

**Comment by dconde7** [comment]
Make sure to always open the project with the .xcworkspace file (generated by CocoaPods) and not the .xcodeproj, otherwise you’ll encounter build errors.

**Comment by repoiso** [comment]
I use the .xcworkspace file.

the pod file:
# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'RepoCyber' do
  use_frameworks!

  # Pods for RepoCyber
  pod 'Backendless', '~> 4.0'
  pod 'Lumina'
end

give me errors on lumina, after pod install

**Comment by eman6576** [comment]
@repoiso CoreML is only available for iOS 11. So for your project, you would need to upgrade your deployment target.

**Comment by dokun1** [comment]
@eman6576 this *should* work for iOS 10 as well, since the properties available only in iOS 11 are wrapped in `#available` or `@available`.

@repoiso can you post a screenshot of the xcode error that you get? Also, are you trying to build this for an ARM device, or your simulator?

**Comment by dokun1** [comment]
@repoiso just FYI - i have set up CI to build the framework for iOS 11.1 and iOS 10.3.1, and the master branch is in a passing state. Have you tried building a sample app with Lumina in iOS 10 with another dependency manager, such as Carthage?

I will close this issue in 10 days given inactivity.
