### ISSUE TITLE
Iphone X support

### ISSUE THREAD

**Issue by arvidurs** [dokun1/Lumina#71]
Please adjust the UI Buttons to respect the safemargins for iPhoneX. 

Thanks

**Comment by dokun1** [comment]
Hi @arvidurs! Thank you for reporting this issue.

Could you provide a little bit more information? Additionally, can you tell me if #69 did not fix this issue already?

I do not personally have an iPhone X, so I cannot test this myself. I think this means I need to build a version of this that works in the simulator so I can test the UI buttons around it, but please be a little more clear about what you are saying.

**Comment by arvidurs** [comment]
Hi David, 
sorry about not being more specific regarding the issue. 
I have checked #69 and they are still very very close to the borders. Just some padding left/right and from the top would help a lot. It might be a minor thing, but it's just something I thought to flag. 

Thanks for the awesome framework btw!

**Comment by dokun1** [comment]
Fair point. I'll take a look this week and see what I can come up with. In addition to meeting some friends who have these fancy new phones later this week, I'll work up some simulator support.

**Comment by dokun1** [comment]
@arvidurs sorry I haven't gotten to it yet this week! Been a bit snowed under with other things coming down on me, but I can try to make a change sometime this week.

Of course, feel free to fork and take a swing at making some changes yourself if you'd like :-]
