### ISSUE TITLE
is there a way to save 3 seconds before and and after detection found?

### ISSUE THREAD

**Issue by steve21124** [dokun1/Lumina#79]
is there a way to save 3 seconds before and and after detection found? if it is, what will be the way to do it? and it will be continuous camera used but only save video if detection found

**Comment by steve21124** [comment]
Thanks for the response. Yes, seems like saving frame by frame will be the way. but it seems like it will be slow.
For example like security camera, it save 5 seconds videos before the actual detection and keep recording 5 seconds after detection. so Total 10 seconds.

**Comment by dokun1** [comment]
@steve21124 please let me know if you come up with an implementation for this - I'd love to see it.

Because this isn't quite in the immediate roadmap for Lumina, I'm going to close this issue at the end of the day today, unless you'd like to discuss it further 😄

**Comment by steve21124** [comment]
Thanks, i have not implemented, once i have code it, i will create pull request
