### ISSUE TITLE
Depth data not delivered to captured delegate

### ISSUE THREAD

**Issue by cansik** [dokun1/Lumina#87]
In the current release (1.2.1) and also in the actual version of the repository, it is not possible to capture depth images in the `captured` delegate.

## Expected Behavior
If `camera.captureDepthData = true` is set, in the `captured` delegate the depth data should not be null:

```swift
if let data = depthData as? AVDepthData {
	guard let depthImage = data.depthDataMap.normalizedImage(with: controller.position) else {
	    print("could not convert depth data")
	    return
	}
}
```

## Current Behavior
The depth data is always not set (`Optional<Any>`).

## Steps to Reproduce (for bugs)
Check out the [ViewController.swift](https://github.com/cansik/ios-depth-recorder/blob/f26042467f2561aefb63428aa9c959637a5b6376/DepthRecorder/ViewController.swift) of my test project.

## Your Environment
Tested on iPhone X.

**Comment by cansik** [comment]
Never-mind, I missed the fact that I have to adjust the camera resolution to capture depth images:

```swift
camera.resolution = .vga640x480
```

Would be nice if that is documented somewhere.

**Comment by dokun1** [comment]
Hi @cansik!! Thanks for raising an issue, and I'm glad you were able to figure out the solution.

This is actually documented on the project's readme here: https://github.com/dokun1/Lumina#functionality

Please note the comments after the options regarding depth data. I understand your frustration with the resolution bit - I would love to think of a better way to graph out some of the feature dependencies here!

Setting up a page with full documentation is on the cards, and should be done eventually. For now, the README should be thorough enough.

Last question - how did you arrive at v1.2.1? v1.3.1 was tagged in June.

**Comment by cansik** [comment]
@dokun1 Thank you for the answer. Your 1.2.1 is marked as latest release:

![image](https://user-images.githubusercontent.com/5220162/43889389-530588d4-9bc4-11e8-9732-8f035f863e47.png)

I now saw that there are newer ones, but I now work with the head of the master.
