### ISSUE TITLE
Flash

### ISSUE THREAD

**Issue by aabanaag** [dokun1/Lumina#90]
**Describe the bug**
When tapping the torch button causes the app to crash with the error of flashMode must be set to a value present in the supportedFlashModes array.

**To Reproduce**
1. Show LuminaController (with torch not hidden)
2. Tap torch button (either turning it on or using the auto)
3. Tap shutter button (the app will crash)

**Expected behavior**
It should take a picture with the flash on.

**Smartphone (please complete the following information):**
iPad 2017 (12.1)

**Comment by dokun1** [comment]
Hi @aabanaag thank you for opening this issue! Can you please go back and edit the issue to provide the rest of the information I need? I don't have anything meaningful for *Steps to reproduce* or information about the device this error occurs on. Thank you!

**Comment by aabanaag** [comment]
@dokun1 hey, sorry I was swamped with other things to do. Anyways hope my latest update can help.

**Comment by aabanaag** [comment]
Closing this issue as this was due to the fact that my app was running on a iPad which has no flash module. Although I think this should be handled since `AVCaptureDevice.hasFlash` checks if the device has flash module or not.
