### ISSUE TITLE
allow public accessors to torch state and zoom level (get and set)

### ISSUE THREAD

**Issue by drmarkpowell** [dokun1/Lumina#94]
**Is your feature request related to a problem? Please describe.**
For our app, we would like to run Lumina as an embedded view controller within a custom UIVC and control its torch and zoom level via our own external UI buttons or similar.

**Describe the solution you'd like**
In addition to the LuminaViewController internal buttons, we would like to be able to set/get the LuminaCamera torch state and current zoom level programatically.

**Describe alternatives you've considered**
We considered using the existing LuminaViewController buttons but we're embedding the Lumina VC in a small space and the internal buttons are occluding the camera view too much (we are scanning barcodes with it).

**Additional context**
We are using Lumina for this app mainly to scan barcodes, within a custom UIViewController that presents a few other custom controls for related things.

Would making the LuminaCamera public be appropriate, or would adding additional set/get method to LuminaViewController be more acceptable? I'd be happy to fire a PR your way.

**Comment by dokun1** [comment]
Hey! Thank you so much for this issue and tagging this.

I think the most appropriate way forward would be to add setters and getters for those levels. I think `LuminaCamera` is and should be private to prevent misuse of the interface. I have seen other use cases similar to this with the simple presence of other buttons on the UI, thanks to @gerriet and his contribution.

Let me know if you agree with this - happy to review a PR of it!
